os:
  - linux

language: php

php:
  - '7.2'
  
before_script:
  - cp .env.example .env
  - mysql -e 'create database bdproducts;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate:refresh 
  - php artisan db:seed 

script:
  - vendor/bin/phpunit
