os:
  - linux

language: php

php:
  - '7.2'
  
before_script:
  - cp .env.example .env
  - mysql -e 'create database bdproducts;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
